import '@mantine/core/styles.css';
import {theme} from "../theme";
import {ColorSchemeScript, MantineProvider} from "@mantine/core";
import {Notifications} from "@mantine/notifications";
import {Providers} from "@/lib/providers";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default async function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode,
}) {
    return (
            <html lang="en" suppressHydrationWarning={true}>
                <head>
                    <ColorSchemeScript/>
                    <link rel="shortcut icon" href="/favicon.svg"/>
                    <meta
                        name="viewport"
                        content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
                    />
                </head>
                <body>
                <Providers>
                    <MantineProvider theme={theme}>
                        <Notifications/>
                        {children}
                    </MantineProvider>
                </Providers>
                </body>
            </html>
    )
}
