import LoginForm from "@/components/LoginForm/LoginForm";

export const metadata = {
    title: 'Next.js | LoginForm',
    description: 'Generated by Next.js',
}

export default function LoginPage() {
    return <LoginForm />
}