import '@mantine/core/styles.css';
import {Shell} from "@/components/Shell/Shell";
import { createClient } from "@/lib/utils/supabase/server"
import {redirect} from "next/navigation";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default async function AdminLayout({
                                              children,
                                          }: {
    children: React.ReactNode
}) {
    const supabase = createClient()

    const { data, error } = await supabase.auth.getUser()
    if (error || !data?.user) {
        redirect('/')
    }

    const { user } = data
    return (
        <Shell user={user}>{children}</Shell>
    )
}
