import '@mantine/core/styles.css';
import {Shell} from "@/components/Shell/Shell";
import {cookies} from 'next/headers'
import {Database} from '@/lib/database.types'
import {createServerComponentClient} from "@supabase/auth-helpers-nextjs";
import {redirect} from "next/navigation";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default async function AdminLayout({
                                              children,
                                          }: {
    children: React.ReactNode
}) {
    const supabase = createServerComponentClient<Database>({cookies})

    const {
        data: {user},
    } = await supabase.auth.getUser()

    if(!user){
        redirect('/auth/login')
    }

    return (
        <Shell user={user}>{children}</Shell>
    )
}
