import '@mantine/core/styles.css';
import {Shell} from "../../components/Shell/Shell";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function AdminLayout({
                                        children,
                                    }: {
    children: React.ReactNode
}) {
    return (
        <Shell>{children}</Shell>
    )
}
